### ISSUE TITLE
How to deploy on AWS Lambda itself? Can you add instructions in the README?

### ISSUE THREAD

**Issue by sopko16** [gbdevw/python-fastapi-aws-lambda-container#3]
Hey,

I cannot seem to get this to work when deployed on AWS lambda: I do/can get the Docker Container onto ECR, and I can see all the steps you have in the existing README work for me. I just cannot seem to get the Lambda on AWS part to work... I think it should involve the need for use of API gateway under "Trigger" and possibly adding a "proxy" under API Gateway settings, but yeah I just cannot seem to get that to work. *Also in testing it, I tried modifying this and changing things to use GET and /hello/, and also this in that field (just in case): https://github.com/gbdevw/python-fastapi-aws-lambda-container#test-the-lambda 
but no luck
![image](https://user-images.githubusercontent.com/6151913/154346863-e5e9c340-902c-4896-988a-3b1caf4350bc.png)

If you can add that, it would be awesome, but I can see why you might not, since this is a personal project. Thanks for the help here, if you can.

**Comment by gbdevw** [comment]
Hello, thank you for your message :)

You are right on both things: 

1. You need to use AWS API Gateway as the front door for the API.
2. A guide to show how to deploy the API on AWS would be a great add

So [here it is](https://github.com/gbdevw/python-fastapi-aws-lambda-container/blob/main/documentation/deployment/awsconsole/aws_console.md).

Please let me know if it worked for you and I will close the issue.
